modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/CuriousShulkerBoxes/issues"
logoFile="curioussb_icon.png"
[[mods]]
modId="curiousshulkerboxes"
version="${version}"
displayName="Curious Shulker Boxes"
displayURL="https://github.com/TheIllusiveC4/CuriousShulkerBoxes"
authors="C4"
description='''
Adds curio support for Shulker Boxes for easier access and management.
'''
[[dependencies.curiousshulkerboxes]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiousshulkerboxes]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiousshulkerboxes]]
    modId="curios"
    mandatory=true
    versionRange="${curios_version_range}"
    ordering="NONE"
    side="BOTH"